package com.doku.sdk.dokujavalibrary.enums;

public enum VaChannelEnum {
    VIRTUAL_ACCOUNT_BCA,
    VIRTUAL_ACCOUNT_BANK_MANDIRI,
    VIRTUAL_ACCOUNT_BANK_SYARIAH_MANDIRI,
    VIRTUAL_ACCOUNT_BANK_BRI,
    VIRTUAL_ACCOUNT_BANK_BNI,
    VIRTUAL_ACCOUNT_BANK_DOKU,
    VIRTUAL_ACCOUNT_PERMATA,
    VIRTUAL_ACCOUNT_CIMB,
    VIRTUAL_ACCOUNT_DANAMON;

}
