package com.doku.sdk.dokujavalibrary.enums;

public enum VaChannelEnum {
    VIRTUAL_ACCOUNT_BCA,
    VIRTUAL_ACCOUNT_BANK_MANDIRI,
    VIRTUAL_ACCOUNT_BANK_BRI,
    VIRTUAL_ACCOUNT_BANK_BNI,
    VIRTUAL_ACCOUNT_BANK_DANAMON,
    VIRTUAL_ACCOUNT_BANK_PERMATA,
    VIRTUAL_ACCOUNT_MAYBANK,
    VIRTUAL_ACCOUNT_BNC,
    VIRTUAL_ACCOUNT_BTN,
    VIRTUAL_ACCOUNT_BSI,
    VIRTUAL_ACCOUNT_BANK_CIMB,
    VIRTUAL_ACCOUNT_SINARMAS,
    VIRTUAL_ACCOUNT_DOKU,
    VIRTUAL_ACCOUNT_BSS;

}
